config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: %i[new create show]
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'flights#index'
  
  get '/flights', to: 'flights#index'

  get 'users/id', to: 'users#show', as: 'profile'


end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :arrival_airport, class_name: 'Airport'
  belongs_to :departure_airport, class_name: 'Airport'
  has_many :bookings
  has_many :passengers, through: :bookings

  validates :flight_start, presence: true
  validates :flight_duration, presence: true, numericality: { in: 1200..28800 }

  def self.select_flight_dates
    Flight.pluck('flight_start').sort.map { |a| a.strftime('%d.%m.%Y') }.uniq
  end

  def self.search(query)
    if query
      flights = Flight.all.includes(:arrival_airport, :departure_airport).order(:flight_start)
      flights = flights.where(arrival_airport_id: query[:arrival_airport]) unless query[:arrival_airport] == ''
      flights = flights.where(departure_airport_id: query[:departure_airport]) unless query[:departure_airport] == ''
      date = query[:flight_start].to_datetime
      flights = flights.where(flight_start: date.beginning_of_day..date.end_of_day) if date
      flights
    else
      Flight.all.includes(:arrival_airport, :departure_airport).order(:flight_start)
    end
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @pagy, @flights = pagy(Flight.search(params[:search]))
    @tickets_num = params[:search] ? params[:search][:tickets_num] : 0
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_flight.html.erb
<div>
  <p>From: <%= "#{flight.departure_airport.name}" %></p>
  <p>Departure at: <%= "#{flight.flight_start}" %></p>
  <p>Duration: <%= "#{ActiveSupport::Duration.build(flight.flight_duration).inspect}" %></p>
  <p>To: <%= "#{flight.arrival_airport.name}" %></p>
  <p>Arrival at: <%= flight.flight_start + flight.flight_duration %></p>
  <div class='w-100 d-flex justify-content-center align-items-center'>
    <%= button_to 'Book flight',
        new_booking_path,
        method: 'get',
        params: { flight_id: flight.id,
                  id: 'booking_button',
                  tickets_num: @tickets_num },
        class: 'btn btn-outline-success w-10 mt-5' %>
  </div>
</div>

app/views/flights/_flight_search.html.erb
<%= form_with scope: :search, url: flights_path, method: 'GET' do |f| %>
  <div class='input-group mb-3'>
    <%= f.label :departure_airport, 'From: ', class: 'input-group-text' %>
    <%= f.select :departure_airport, Airport.all.order('name').map { |a| [a.name, a.id] }, include_blank: true %>
    <%= f.label :arrival_airport, 'To: ', class: 'input-group-text' %>
    <%= f.select :arrival_airport, Airport.all.order('name').map { |a| [a.name, a.id] }, include_blank: true %>
    <%= f.label :flight_start, 'Date: ', class: 'input-group-text' %>
    <%= f.select :flight_start, Flight.select_flight_dates, include_blank: true %>
    <%= f.label :tickets_num, 'Number of passengers: ', class: 'input-group-text' %>
    <%= f.select :tickets_num, 1..4, include_blank: true %>
    <%= f.submit 'Search', class: 'btn btn-search btn-danger' %>
  </div>
<% end %>

app/views/flights/index.html.erb
<div class='d-grid gap-2'>
  <div class='d-flex justify-content-center mt-3'>
    <%= render 'flights/flight_search' %>
  </div>
  <div class='mb-5 text-monospace'>
    <% unless @flights.empty? %>
      <% @flights.each do |flight| %>
        <div class='container bg-light mb-3'>
          <%= render flight %>
        </div>
      <% end %>
    <% else %>
      <p class='text-center mt-5 mb-3'>No available flights!</p>
    <% end %>
  </div>
  <div class='d-flex justify-content-center bg-light'>
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>